/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import NapakalakiGame.CombatResult;
import NapakalakiGame.Napakalaki;

/**
 *
 * @author Carmen Biedma
 */
public class NapakalakiView extends javax.swing.JFrame {

    /**
     * Creates new form NapakalakiView
     */
    
    private Napakalaki napakalakiModel;
    
    public NapakalakiView() {
        initComponents();
    }
    
    public void setNapakalaki(Napakalaki np ){
        napakalakiModel=np;
        
        if(napakalakiModel.getCurrentMonster()!=null) 
            monsterView1.setMonster(np.getCurrentMonster());
        
        playerView1.setPlayer(np.getCurrentPlayer(),this);
        playerView1.setNapakalakiModel(np);
        
        botonMeetTheMonster.setEnabled(true);
        
        update();
        
        repaint();
    }

    public void update(){
        if(playerView1.getPBadConsequenceView().getPendingBadConsequence() != null && playerView1.getPBadConsequenceView().getPendingBadConsequence().isEmpty()){
            botonNextTurn.setEnabled(true);
        }
        playerView1.update();
        repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView1 = new GUI.MonsterView();
        playerView1 = new GUI.PlayerView();
        botonMeetTheMonster = new javax.swing.JButton();
        botonCombat = new javax.swing.JButton();
        botonNextTurn = new javax.swing.JButton();
        CombatResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout playerView1Layout = new javax.swing.GroupLayout(playerView1);
        playerView1.setLayout(playerView1Layout);
        playerView1Layout.setHorizontalGroup(
            playerView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        playerView1Layout.setVerticalGroup(
            playerView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 429, Short.MAX_VALUE)
        );

        botonMeetTheMonster.setText("Meet the Monster");
        botonMeetTheMonster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMeetTheMonsterActionPerformed(evt);
            }
        });

        botonCombat.setText("Combat");
        botonCombat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCombatActionPerformed(evt);
            }
        });

        botonNextTurn.setText("Next Turn");
        botonNextTurn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNextTurnActionPerformed(evt);
            }
        });

        CombatResult.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(playerView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(botonMeetTheMonster)
                                .addGap(30, 30, 30)
                                .addComponent(botonCombat)
                                .addGap(32, 32, 32)
                                .addComponent(botonNextTurn)
                                .addGap(0, 87, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CombatResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(CombatResult)
                .addGap(77, 77, 77)
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonMeetTheMonster)
                    .addComponent(botonCombat)
                    .addComponent(botonNextTurn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMeetTheMonsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMeetTheMonsterActionPerformed
        monsterView1.setVisible(true);
        botonCombat.setEnabled(true);
        botonMeetTheMonster.setEnabled(false);
    }//GEN-LAST:event_botonMeetTheMonsterActionPerformed

    private void botonCombatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCombatActionPerformed
         CombatResult cr = napakalakiModel.developCombat();
        labelCombatResult.setText(cr.toString());
        setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_botonCombatActionPerformed

    private void botonNextTurnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNextTurnActionPerformed
        boolean success = napakalakiModel.nextTurn();
        if(success)
            setNapakalaki(napakalakiModel);
    }//GEN-LAST:event_botonNextTurnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CombatResult;
    private javax.swing.JButton botonCombat;
    private javax.swing.JButton botonMeetTheMonster;
    private javax.swing.JButton botonNextTurn;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    // End of variables declaration//GEN-END:variables
}
